spring:
  application:
  name: body-switch

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # h2
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true

  # db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:body-switch
    username: sa
    password:

# logging
logging.level:
  org.hibernate.SQL: debug